---
- hosts: all
  sudo: yes
  tasks:
  - name: install needed Ubuntu .debs
    apt: >-
      pkg={{ item }}
      state=present
      update_cache=yes
    with_items:
      - unattended-upgrades
      - git
      - python-dev
      - python-pip
