---
- hosts: all
  sudo: yes
  tasks:
  - name: install needed Ubuntu .debs
    apt: pkg={{ item }} state=present
    with_items:
      - unattended-upgrades
      - git
      - python-dev
      - python-pip
